package dsttime.gui;

import dsttime.CostCounter;
import dsttime.PhoneCostStrategy;
import dsttime.SimplePhoneCostStrategy;
import dsttime.TransMillToSimple;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author robinhood, yfwz100
 */
public class DSTFrame extends javax.swing.JFrame
{

    private Timer currentDateTimer;
    private PhoneCostStrategy phonecost;
    private CostCounter costCounter;
    private Calendar currentDate = Calendar.getInstance(TimeZone.getTimeZone("Asia/Hong_Kong"));
    private boolean DSTFlag = false;
    
    private DateFormat df = new SimpleDateFormat("y-M-d HH:mm:ss Z");

    static {
        TimeZone.setDefault(TimeZone.getTimeZone("Asia/Hong_Kong"));
    }

    /**
     * Creates new form DSTFrame
     */
    public DSTFrame()
    {
        JFrame.setDefaultLookAndFeelDecorated(true);
        initComponents();
        this.phonecost = new SimplePhoneCostStrategy();
        this.costCounter = new CostCounter();
        currentDateTimer = new Timer(1000, new ActionListener()
        {

            @Override
            public void actionPerformed(ActionEvent e)
            {
                currentDate.add(Calendar.SECOND, 1);
                currentDateBtn.setText(df.format(currentDate.getTime()));
                if(DSTFrame.this.costCounter.currentTime()>20*60*60*1000)
                {
                    costCounter.Stop();
                    JOptionPane.showMessageDialog(DSTFrame.this, "通话时间已经超过20小时，珍爱生命！");
                    DSTFrame.this.commToggleBtn.setSelected(false);
                }
                timerLabel.setText(TransMillToSimple.TransMill(DSTFrame.this.costCounter.currentTime()));
            }
        });
        currentDateTimer.setInitialDelay(0);
        currentDateTimer.setRepeats(true);
        currentDateTimer.start();

        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dateSetupDialog = new javax.swing. JDialog(this);
        jLabel6 = new javax.swing.JLabel();
        currentDateSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        currentDateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        commToggleBtn = new javax.swing.JToggleButton();

        dateSetupDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dateSetupDialog.setTitle("设置当前时间");
        dateSetupDialog.setModal(true);
        dateSetupDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dateSetupDialog.setResizable(false);
        dateSetupDialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                dateSetupDialogActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                dateSetupDialogClosed(evt);
            }
        });

        jLabel6.setText("当前时间：");

        currentDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        currentDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(currentDateSpinner, "y-M-d HH:mm:ss"));

        jButton1.setText("确定");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                changeDateActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new DefaultComboBoxModel(TimeZone.getAvailableIDs()));
        jComboBox2.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel4.setText("时区");

        javax.swing.GroupLayout dateSetupDialogLayout = new javax.swing.GroupLayout(dateSetupDialog.getContentPane());
        dateSetupDialog.getContentPane().setLayout(dateSetupDialogLayout);
        dateSetupDialogLayout.setHorizontalGroup(
            dateSetupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateSetupDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dateSetupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateSetupDialogLayout.createSequentialGroup()
                        .addGroup(dateSetupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(dateSetupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentDateSpinner, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        dateSetupDialogLayout.setVerticalGroup(
            dateSetupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateSetupDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dateSetupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dateSetupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        dateSetupDialog.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("计时器");
        setResizable(false);

        jLabel1.setText("当前时间：");

        currentDateBtn.setText("初始化请稍后");
        currentDateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        currentDateBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentDateBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                currentDateBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("计时：");

        jLabel3.setText("当前费用：");

        timerLabel.setFont(new java.awt.Font("Segoe WP Black", 0, 36)); // NOI18N
        timerLabel.setText("00:00");

        jLabel5.setText("0.00");

        commToggleBtn.setText("开始通话");
        commToggleBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                commToggleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commToggleBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentDateBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(timerLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentDateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(timerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commToggleBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentDateBtnActionPerformed
        dateSetupDialog.pack();
        dateSetupDialog.setLocationRelativeTo(this);
        dateSetupDialog.setVisible(true);
    }//GEN-LAST:event_currentDateBtnActionPerformed

    private void commToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commToggleBtnActionPerformed
        if (this.commToggleBtn.getText().equals("开始通话")) {
            this.commToggleBtn.setText("结束通话");
            this.costCounter.reset();
            this.costCounter.Start();
            this.timerLabel.setText("00:00");
            this.jLabel5.setText("0.0");
            this.currentDateBtn.setEnabled(false);
        } else {
            this.commToggleBtn.setText("开始通话");
            this.costCounter.Stop();
            Long duration = DSTFrame.this.costCounter.getDuration();
            Long durationMinute = duration / 1000 / 60;
            if (duration / 1000 % 60 != 0) {
                durationMinute++;
            }
            DSTFrame.this.jLabel5.setText(DSTFrame.this.phonecost.getCost(durationMinute).toString());
            this.currentDateBtn.setEnabled(true);
        }

    }//GEN-LAST:event_commToggleBtnActionPerformed

    private void changeDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDateActionPerformed
        Date d=(Date)this.currentDateSpinner.getValue();
        this.currentDate.setTime(d);
        dateSetupDialog.dispose();
    }//GEN-LAST:event_changeDateActionPerformed

    private void dateSetupDialogActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dateSetupDialogActivated
        currentDateTimer.stop();
        currentDateSpinner.setValue(currentDate.getTime());
    }//GEN-LAST:event_dateSetupDialogActivated

    private void dateSetupDialogClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dateSetupDialogClosed
        currentDateTimer.start();
    }//GEN-LAST:event_dateSetupDialogClosed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jComboBox2ItemStateChanged
    {//GEN-HEADEREND:event_jComboBox2ItemStateChanged
        String timezone = (String) jComboBox2.getSelectedItem();
        TimeZone tz = TimeZone.getTimeZone(timezone);

        this.currentDate.setTimeZone(tz);
        currentDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(currentDateSpinner, "y-M-d HH:mm:ss"));
        df.setTimeZone(tz);
        TimeZone.setDefault(tz);
        
        this.currentDateSpinner.setValue(this.currentDate.getTime());
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new DSTFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton commToggleBtn;
    private javax.swing.JButton currentDateBtn;
    private javax.swing.JSpinner currentDateSpinner;
    private javax.swing.JDialog dateSetupDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
